{
  "services": {
    "cloud-weather-postgres": {
      "environment": [
        "POSTGRES_DATABASE=cloud_weather_dev", 
        "POSTGRES_USER=cloud", 
        "POSTGRES_PASSWORD=cloud"
      ], 
      "image": "debezium/postgres:13-alpine", 
      "ports": [5432:5432], 
      "volumes": [
        "postgres-data:/data/db"
      ]
    }
  }, 
  "version": "3", 
  "volumes": {
    "postgres-data": null
  }
}